name: Windows (MSYS2) build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windows-msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-qt6-base
            mingw-w64-x86_64-qt6-tools

      - name: Build (Qt6 / MinGW)
        run: |
          export PATH=/mingw64/bin:$PATH
          mkdir -p build-win && cd build-win
          cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build . -j
          mkdir -p package && cp ColorLab7.exe package/
          # Qt6 工具名称是 windeployqt6（注意这个 6）
          windeployqt6 --release package/ColorLab7.exe
          cd package
          zip -r ../ColorLab7-win64.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: ColorLab7-win64
          path: build-win/ColorLab7-win64.zip
